[tools]
# Language, Package Manager
bun = "latest"
pnpm = "latest"
node = "latest"
rust = "latest"
go = "latest"

# Cli, TUI tools
bat = "latest"
delta = "latest"
eza = "latest"
fd = "latest"
bottom = "latest"
ripgrep = "latest"
sd = "latest"
zoxide = "latest"
fzf = "latest"
gitui = "latest"
zellij = "latest"
dust = "latest"
lazygit = "latest"
neovim = "latest"
jq = "latest"
yq = "latest"
"cargo:rust_tree" = "latest"

# AI tools
codex = "latest"
gemini-cli = "latest"
opencode = "latest"
claude = "latest"
marp-cli = "latest"
herdr = "latest"
"npm:hunkdiff" = "latest"
github-cli = "latest"
"npm:@openai/codex" = "latest"

