[tools]
# Registry tool names (mise registry)
bat = "latest"
delta = "latest"
eza = "latest"
fd = "latest"
bottom = "latest"
ripgrep = "latest"
sd = "latest"
zoxide = "latest"
skim = "latest"
gitui = "latest"
starship = "latest"
zellij = "latest"
dust = "latest"
broot = "latest"
lazygit = "latest"
neovim = "latest"
jq = "latest"
yq = "latest"
