-- Generated by nwg-displays on 2026-07-17 at 10:31:44. Do not edit manually.

hl.monitor({
    output = "desc:Lenovo Group Limited 0x403C",
    mode = "2240x1400@60.02",
    position = "4604x1440",
    scale = 1.46
})
hl.monitor({
    output = "desc:HP Inc. OMEN 27q CNC3201642",
    mode = "2560x1440@59.95",
    position = "4096x0",
    scale = 1.0
})
