# Hyprland Autostart Applications

# ==========================================
# Core Services
# ==========================================
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# ==========================================
# User Interface
# ==========================================
# exec-once = waybar # Status Bar
exec-once = dunst # Notification
exec-once = swww-daemon && swww img ~/.config/hypr/wallpapers/default.jpg # Wallpaper
exec-once = gnome-keyring-daemon --start --components=secrets,pkcs11,ssh
# ==========================================
# Polkit Agent
# ==========================================
exec-once = hyprpolkitagent

# ==========================================
# Clipboard
# ==========================================
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# ==========================================
# XDG Portal
# ==========================================
exec-once = dbus-update-activation-environment --all
exec-once = sleep 1 && /usr/lib/xdg-desktop-portal-hyprland

# ==========================================
# Other
# ==========================================
exec-once = nm-applet --indicator # Network
exec-once = blueman-applet # Bluetooth

# Terminal Quake Mode
exec-once = [workspace special:quake silent] ghostty
