# Custom Window Rules

# ==========================================
# Floating Windows
# ==========================================
windowrule = float on, match:class pavucontrol
windowrule = float on, match:title Picture-in-Picture
windowrule = float on, match:class thunar, match:title (Open File|Save File|Select File|Select Folder|ファイルを開く|保存).*
windowrule = float on, match:class imv
windowrule = float on, match:class mpv

windowrule = float on, match:class xdg-desktop-portal-gtk
windowrule = center on, match:class xdg-desktop-portal-gtk

# ==========================================
# Opacity
# ==========================================
windowrule = opacity 0.9, match:class com.mitchellh.ghostty
windowrule = opacity 0.75, match:workspace special:quake

